# Generated by Django 3.2 on 2023-02-25 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='CategoryImage/', verbose_name='ImagePro'),
        ),
        migrations.AlterField(
            model_name='category',
            name='published_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 25, 18, 59, 0, 997530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='published_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 25, 18, 59, 0, 997530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 25, 18, 59, 0, 997530, tzinfo=utc)),
        ),
    ]
