# Generated by Django 3.2 on 2023-02-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230225_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
